name: Build VNC/noVNC image

on:
  push:
    branches: [ main ]
    tags:
      - "v*"
    paths:
      - Dockerfile
      - container/**
      - vnc_novnc/**
      - scripts/**
      - pyproject.toml
      - .github/workflows/build-image.yaml

  workflow_dispatch:

jobs:
  build_and_push_image:
    name: Build and push image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/debian
          tags: |
            type=raw,value=12-vnc-novnc
            type=ref,event=tag

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
